# Generated by Django 6.1 on 2026-09-01 09:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_courseblock'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='coursefeedback',
            constraint=models.UniqueConstraint(fields=('student', 'course'), name='unique_student_course_feedback'),
        ),
    ]
